const vertexShaderSrc = `#version 300 es
in vec2 aVertexPosition;
out vec2 vUv;

void main() {
  vUv = aVertexPosition * 0.5 + 0.5;
  gl_Position = vec4(aVertexPosition, 0.0, 1.0);
}
`;

function fragmentTemplate(frag) {
  result = `#version 300 es
precision highp float;
out vec4 fragColor;
uniform int time;

uniform int scale;

uniform vec3 c1;
uniform vec3 c2;

vec3 oklab_mix(vec3 lin1, vec3 lin2, float a)
{
    // https://bottosson.github.io/posts/oklab
    const mat3 kCONEtoLMS = mat3(
         0.4121656120,  0.2118591070,  0.0883097947,
         0.5362752080,  0.6807189584,  0.2818474174,
         0.0514575653,  0.1074065790,  0.6302613616);
    const mat3 kLMStoCONE = mat3(
         4.0767245293, -1.2681437731, -0.0041119885,
        -3.3072168827,  2.6093323231, -0.7034763098,
         0.2307590544, -0.3411344290,  1.7068625689);

    // rgb to cone (arg of pow can't be negative)
    vec3 lms1 = pow( kCONEtoLMS*lin1, vec3(1.0/3.0) );
    vec3 lms2 = pow( kCONEtoLMS*lin2, vec3(1.0/3.0) );
    // lerp
    vec3 lms = mix( lms1, lms2, a );
    // gain in the middle (no oklab anymore, but looks better?)
    lms *= 1.0+0.2*a*(1.0-a);
    // cone to rgb
    return kLMStoCONE*(lms*lms*lms);
}

int pmod(int a, int b) {
    int r = a % b;
    return r < 0 ? r + abs(b) : r;
}

void main() {
int x = int(gl_FragCoord.x / float(scale)) * scale;
int y = int(gl_FragCoord.y / float(scale)) * scale;
${frag}
float res = float(result);
fragColor = vec4(oklab_mix(c1, c2, res / 255.0), 1.0);
}
  `;
  console.log(result);
  return result;
}

function compileShader(gl, code, type) {
  const shader = gl.createShader(type);

  gl.shaderSource(shader, code);
  gl.compileShader(shader);

  if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
    console.log(
      `Error compiling ${
        type === gl.VERTEX_SHADER ? "vertex" : "fragment"
      } shader:`,
    );
    console.log(gl.getShaderInfoLog(shader));
  }
  return shader;
}

function buildShaderProgram(gl, shaderInfo) {
  const program = gl.createProgram();

  shaderInfo.forEach((desc) => {
    const shader = compileShader(gl, desc.code, desc.type);

    if (shader) {
      gl.attachShader(program, shader);
    }
  });

  gl.linkProgram(program);

  if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
    console.log("Error linking shader program:");
    console.log(gl.getProgramInfoLog(program));
  }

  return program;
}

function setupShader(canvas, frag, c1, c2, scale) {
  const gl = canvas.getContext("webgl2");

  const shaderSet = [
    {
      type: gl.VERTEX_SHADER,
      code: vertexShaderSrc,
    },
    {
      type: gl.FRAGMENT_SHADER,
      code: fragmentTemplate(frag),
    },
  ];

  const shaderProgram = buildShaderProgram(gl, shaderSet);
  const timeLoc = gl.getUniformLocation(shaderProgram, "time");
  const scaleLoc = gl.getUniformLocation(shaderProgram, "scale");
  const c1Loc = gl.getUniformLocation(shaderProgram, "c1");
  const c2Loc = gl.getUniformLocation(shaderProgram, "c2");

  // Vertex information
  const vertexArray = new Float32Array([
    -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0,
  ]);
  const vertexBuffer = gl.createBuffer();
  gl.bindBuffer(gl.ARRAY_BUFFER, vertexBuffer);
  gl.bufferData(gl.ARRAY_BUFFER, vertexArray, gl.STATIC_DRAW);
  const vertexNumComponents = 2;
  const vertexCount = vertexArray.length / vertexNumComponents;

  // Animation timing
  let time = 0;
  const [r1, g1, b1] = c1.map((a) => a / 255.0);
  const [r2, g2, b2] = c2.map((a) => a / 255.0);

  const animateScene = () => {
    gl.viewport(0, 0, canvas.width, canvas.height);
    gl.clearColor(0.0, 0.0, 0.0, 1.0);
    gl.clear(gl.COLOR_BUFFER_BIT);

    gl.useProgram(shaderProgram);
    gl.uniform1i(timeLoc, time);
    gl.uniform1i(scaleLoc, Math.pow(2, scale));
    gl.uniform3f(c1Loc, r1, g1, b1);
    gl.uniform3f(c2Loc, r2, g2, b2);

    gl.bindBuffer(gl.ARRAY_BUFFER, vertexBuffer);
    aVertexPosition = gl.getAttribLocation(shaderProgram, "aVertexPosition");

    gl.enableVertexAttribArray(aVertexPosition);
    gl.vertexAttribPointer(
      aVertexPosition,
      vertexNumComponents,
      gl.FLOAT,
      false,
      0,
      0,
    );

    gl.drawArrays(gl.TRIANGLES, 0, vertexCount);

    requestAnimationFrame(() => {
      animateScene();
      time++;
    });
  };
  animateScene();
}
function parseCookies(cookieString) {
  const cookies = cookieString.split("; ");
  const cookiesDict = {};
  for (const cookie of cookies) {
    const [key, value] = cookie.split("=", 2);
    cookiesDict[key] = value;
  }
  return cookiesDict;
}

const marketing = "Generated by receipt-math.recurse.com\n\n";
function sendCanvasToPrinter(canvas, text) {
  const csrf = parseCookies(document.cookie).receipt_csrf;
  if (!csrf) {
    alert("Please click 'login' at the top of the page first.");
    return;
  }
  canvas.toBlob(async (blob) => {
    await fetch("https://receipt.recurse.com/text", {
      method: "POST",
      credentials: "include",
      headers: {
        "Content-Type": "application/json",
        "X-CSRF-Token": csrf,
      },
      body: JSON.stringify({
        text: marketing + text,
        coda: "newline",
      }),
    });
    fetch("https://receipt.recurse.com/image", {
      method: "POST",
      credentials: "include",
      headers: {
        "Content-Type": "application/octet-stream",
        "X-CSRF-Token": csrf,
      },
      body: blob,
    });
  }, "image/png");
}

function p(s) {
  const el = document.createElement("p");
  el.innerHTML = s;
  return el;
}

function a(s, url) {
  const el = document.createElement("a");
  el.innerHTML = s;
  el.href = url;
  return el;
}
function setupLoginSection() {
  const csrf = parseCookies(document.cookie).receipt_csrf;
  if (!window.location.origin.match(/.recurse.com\/?$/)) {
    loginDiv.appendChild(
      p(
        'This is not a *.recurse.com subdomain, so it will not be able to make authenticated requests to <a href="https://receipt.recurse.com">https://receipt.recurse.com</a>.',
      ),
    );
    loginDiv.appendChild(
      p(
        'Please visit <a href="https://receipt-tester.recurse.com">https://receipt-tester.recurse.com</a> for the full experience.',
      ),
    );
    return;
  }
  if (csrf) {
    loginDiv.appendChild(p("You are logged in."));
    return;
  }
  loginDiv.appendChild(
    a(
      "login",
      `https://receipt.recurse.com/login?redirect_uri=${window.location.href}`,
    ),
  );
}
